#!/usr/bin/python -u
# hdsp-21xx test script
import time

# clear screen
print u'\x1b' + "[2J"
print "hdsp-21xx"
time.sleep(2)

# blinking
print "bl" + u'\x1b' + "[5m" + "i" + u'\x1b' + "[0m" + "nk"
time.sleep(2)

# intensity
for x in "0123456":
  print u'\x1b' + "[3" + x + "m" + "intensity"
  time.sleep(1)
print u'\x1b' + "[34m"

# fonts
for f in "012":
  print u'\x1b' + "[1" + f + "m"
  for c in range(0xc0, 0xc4):
    print chr(c),
    time.sleep(1)
print u'\x1b' + "[10m"

#cursor
for p in range(1, 33):
  print u'\x1b' + "["  + str(p) + "G*" + u'\x1b' + "[1G"
  time.sleep(1)

print "done"
#not truncated
